data:
  path: build/alternatives/continuous.h5mu
  views:
  - gexp
  - meth
  - crispr
  use_tissue: true
  use_mutations: true
model:
  type: mosa_vae
  output_dir: build/alternatives/kl_warmup_False/outputs
  joint_latent_dim: 8
  num_epochs: 1
  batch_size: 16
  accelerator: cpu
  devices: 1
  random_seed: 42
  views:
    gexp:
      hidden_layer_dims:
      - 16
    meth:
      hidden_layer_dims:
      - 16
    crispr:
      hidden_layer_dims:
      - 16
  use_kl_scheduler: false
  kl_warmup_epochs: 0
  kl_weight_final: 0.001
evaluation:
  test_size: 0.2
  n_folds: 3
